### ISSUE TITLE
PYMM - can't create large shelf size - the shelf is stuck

### ISSUE THREAD

**Issue by moshik1** [IBM/mcas#151] opened 2021-08-23 13:01 UTC
**In sg-pmem2 I created a pool size above 700GB.**
[moshikh@sg-pmem2 experiments]$ ndctl list
[
  {
    "dev":"namespace0.0",
    "mode":"fsdax",
    "map":"dev",
    "size":799063146496,
    "uuid":"8fcfc3e0-c2f5-4f3f-8879-6de7c4581563",
    "sector_size":512,
    "align":2097152,
    "blockdev":"pmem0"
  }
]

**When trying to create a shelf size 530000MB the shelf is stuck (cpu working on 100%)**
>>> s = pymm.shelf('mnist_pymm_posterior',size_mb=530000,pmem_path='/mnt/pmem0',  backend='hstore-cc', force_new='True')
[LOG]: Matching backend exists!
[LOG]: CCA init /home/moshikh/mcas_pymm/src/lib/libccpm/src/cca.cpp:72 0x558accf8cf10 (clear)

**I succeed to create a shelf of size 520000MB instantaneously.**
 >>> s = pymm.shelf('mnist_pymm_posterior',size_mb=520000,pmem_path='/mnt/pmem0',  backend='hstore-cc', force_new='True')
[LOG]: Matching backend exists!
[LOG]: CCA init /home/moshikh/mcas_pymm/src/lib/libccpm/src/cca.cpp:72 0x558accf8cf10 (clear)

**When trying to create a shelf that is larger than "/mnt/pmem" size. The shelf creation fails as expetcted.**
>>> s = pymm.shelf('mnist_pymm_posterior',size_mb=830000,pmem_path='/mnt/pmem0',  backend='hstore-cc', force_new='True')
[LOG]: load_backend: (hstore-cc) (/mnt/pmem0) ()
[LOG]: dax config: [{"path":"/mnt/pmem0","addr":38654705664}]
[LOG]: arena_fs::region_create posix_fallocate: 870334857216: No space left on device
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/shelf.py", line 71, in __init__
    self.mr = MemoryResource(name, size_mb, pmem_path=pmem_path, backend=backend, mm_plugin=mm_plugin, force_new=force_new)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/memoryresource.py", line 95, in __init__
    super().__init__(pool_name=name, size_mb=size_mb, pmem_path=pmem_path, backend=backend, mm_plugin=mm_plugin, force_new=force_new)
RuntimeError: unable to create/open pool

**Comment by dwaddington** [comment] 2021-08-23 15:49
Can you run it through GDB and find out what the CPUU is doing?

**Comment by dwaddington** [comment] 2021-08-24 14:27
As it happens I was able to reproduce the bug. Caused by an instance of this pattern:

    size_t pow2(unsigned i, unsigned j) {
      return 1<<j;
    }


An error because << uses the C integral promotion rules, which are 99% okay for +, 95% okay for *, but very likely wrong for <<.

**Comment by dwaddington** [comment] 2021-08-24 14:27
Fixed with commit: https://github.com/IBM/mcas/commit/468e9a38dd00223e09b592fc835e61df98a594ae

**Closed by dwaddington** 2021-08-24 14:27 UTC
